### PR TITLE
Add foxy, humble and rolling CI

### LINKED ISSUE #40: Adding CI
Hi @youtalk , I'd like to create a new PR adding CI in. Do you have preferences for industrial_ci vs action-ros-ci, or another? My preference would be action-ros-ci, but would be happy to work with any tool you're comfortable with.

### PR DESCRIPTION
**Pull request by ijnek**
This PR adds CI to all active distributions (foxy, humble and rolling).
Changes should be backported to the foxy and humble branches.

Resolves: #40

### CODE REVIEW

**Review by youtalk — APPROVED** [review]
Looking forward to running the CI.

**Comment by ijnek** [comment]
Thanks for the review @youtalk. CI will start off as failures, but we can fix those in follow up PRs.

**Comment by ijnek** [comment]
@Mergifyio backport foxy humble

**Comment by ijnek** [comment]
i'm going to install the Mergify application across all dynamixel-community repositories.

**Comment by ijnek** [comment]
@Mergifyio backport foxy humble

**Pull request merged**
