### PR TITLE
Humble fix

### PR DESCRIPTION
**Pull request by youtalk**
CC @ijnek 
I've temporarily removed dependency on Gazebo and fixed the output argument.

### CODE REVIEW

**Comment by ijnek** [comment]
Thanks for the CC, in regards to the ``output=...`` in the launch file, this is actually a bug in humble, and has been fixed, but a release hasn't been made yet. See https://github.com/ros2/launch/issues/654 for more.

The ROS 2 version in README is changed from Foxy -> Humble, but this should be ROS 2 Rolling on the rolling branch.

The rest looks good, I'm guessing ``ros_ign_gazebo``and ``ign_ros2_control`` were unused dependencies?

**Comment by youtalk** [comment]
> The ROS 2 version in README is changed from Foxy -> Humble, but this should be ROS 2 Rolling on the rolling branch.

Good point. We actually need to change to the Rolling instead.

> The rest looks good, I'm guessing ros_ign_gazeboand ign_ros2_control were unused dependencies?

I couldn't solve the dependencies by rosdep. So I've temporally removed them.

**Comment by ijnek** [comment]
I believe that is due to the name change, ros_ign_gazebo −> ros_gz_sim.

Not sure about ign_ros2_control though, as I dont think it has been renamed to gz_ros2_control yet.

**Comment by youtalk-pfr** [comment]
If you can check the dependency, please make the new PR!

**Pull request merged**
